const englishLang = {
  "behaviour.satellite.type": "Satellite Type: %s",
  "block.gcyr.advanced_fuel_tank": "Advanced Fuel Tank",
  "block.gcyr.advanced_rocket_motor": "Advanced Rocket Motor",
  "block.gcyr.aerospace_aluminium_casing": "Aerospace-grade Aluminium Machine Casing",
  "block.gcyr.airlock_door": "Airlock Door",
  "block.gcyr.basic_fuel_tank": "Basic Fuel Tank",
  "block.gcyr.basic_rocket_motor": "Basic Rocket Motor",
  "block.gcyr.beam_receiver": "Beam Receiver",
  "block.gcyr.cobbled_mercury_rock_stairs": "Cobbled Mercury Rock Stairs",
  "block.gcyr.drone_hangar": "Drone Hangar",
  "block.gcyr.dyson_solar_cell": "Dyson Solar Cell",
  "block.gcyr.dyson_sphere_casing": "Dyson Sphere Casing",
  "block.gcyr.dyson_sphere_maintenance_port": "Dyson Sphere Maintenance Port",
  "block.gcyr.dyson_system_controller": "Dyson System Controller",
  "block.gcyr.elite_fuel_tank": "Elite Fuel Tank",
  "block.gcyr.elite_rocket_motor": "Elite Rocket Motor",
  "block.gcyr.iv_oxygen_spreader": "§9IV Oxygen Spreader",
  "block.gcyr.launch_pad": "Launch Pad",
  "block.gcyr.luna_marker": "Luna",
  "block.gcyr.luv_oxygen_spreader": "§dLuV Oxygen Spreader",
  "block.gcyr.mars_marker": "Mars",
  "block.gcyr.mars_regolith": "Martian Regolith",
  "block.gcyr.martian_cobblestone": "Cobbled Martian Rock",
  "block.gcyr.martian_cobblestone_slab": "Cobbled Martian Rock Slab",
  "block.gcyr.martian_cobblestone_stairs": "Cobbled Martian Rock Stairs",
  "block.gcyr.martian_rock": "Martian Rock",
  "block.gcyr.martian_rock_button": "Martian Rock Button",
  "block.gcyr.martian_rock_slab": "Martian Rock Slab",
  "block.gcyr.martian_rock_stairs": "Martian Rock Stairs",
  "block.gcyr.mercury_cobblestone_slab": "Cobbled Mercury Rock Slab",
  "block.gcyr.mercury_marker": "Mercury",
  "block.gcyr.mercury_rock": "Mercury Rock",
  "block.gcyr.mercury_rock_button": "Mercury Rock Button",
  "block.gcyr.mercury_rock_slab": "Mercury Rock Slab",
  "block.gcyr.mercury_rock_stairs": "Mercury Rock Stairs",
  "block.gcyr.moon_cobblestone": "Cobbled Lunar Stone",
  "block.gcyr.moon_cobblestone_slab": "Cobbled Lunar Stone Slab",
  "block.gcyr.moon_cobblestone_stairs": "Cobbled Lunar Stone Stairs",
  "block.gcyr.moon_sand": "Lunar Sand",
  "block.gcyr.moon_stone": "Lunar Stone",
  "block.gcyr.moon_stone_button": "Lunar Stone Button",
  "block.gcyr.moon_stone_slab": "Lunar Stone Slab",
  "block.gcyr.moon_stone_stairs": "Lunar Stone Stairs",
  "block.gcyr.opv_oxygen_spreader": "§9§lOpV Oxygen Spreader",
  "block.gcyr.prb_underground_mushroom": "Prb Underground Mushroom",
  "block.gcyr.rocket_scanner": "Rocket Scanner",
  "block.gcyr.seat": "Seat",
  "block.gcyr.space_elevator": "Space Elevator",
  "block.gcyr.space_elevator_support": "Space Elevator Support",
  "block.gcyr.space_station_packager": "Space Station Packager",
  "block.gcyr.stainless_evaporation_casing": "Stainless Evaporation Casing",
  "block.gcyr.uev_oxygen_spreader": "§aUEV Oxygen Spreader",
  "block.gcyr.uhv_oxygen_spreader": "§4UHV Oxygen Spreader",
  "block.gcyr.uiv_oxygen_spreader": "§2UIV Oxygen Spreader",
  "block.gcyr.uv_oxygen_spreader": "§3UV Oxygen Spreader",
  "block.gcyr.uxv_oxygen_spreader": "§eUXV Oxygen Spreader",
  "block.gcyr.venus_cobblestone": "Cobbled Venus Rock",
  "block.gcyr.venus_cobblestone_slab": "Cobbled Venus Rock Slab",
  "block.gcyr.venus_cobblestone_stairs": "Cobbled Venus Rock Stairs",
  "block.gcyr.venus_marker": "Venus",
  "block.gcyr.venus_rock": "Venus Rock",
  "block.gcyr.venus_rock_button": "Venus Rock Button",
  "block.gcyr.venus_rock_slab": "Venus Rock Slab",
  "block.gcyr.venus_rock_stairs": "Venus Rock Stairs",
  "block.gcyr.venus_sand": "Venus Sand",
  "block.gcyr.venusian_regolith": "Venusian Regolith",
  "block.gcyr.zpm_oxygen_spreader": "§cZPM Oxygen Spreader",
  "entity.gcyr.rocket": "Rocket",
  "gcyr.alpha_centauri": "Alpha Centauri",
  "gcyr.condition.requires_dyson_sphere.false": "Requires no Dyson Sphere to be active",
  "gcyr.condition.requires_dyson_sphere.true": "Requires active Dyson Sphere",
  "gcyr.condition.space": "Requires machine to be in space",
  "gcyr.machine.satellite_jammer.jammed": "Jammed %s",
  "gcyr.machine.satellite_jammer.position": "At %s",
  "gcyr.multiblock.rocket.build": "Scan Rocket",
  "gcyr.multiblock.rocket.unbuild": "Destroy Rocket",
  "gcyr.multiblock.space_shuttle.launch.0": "Travel to selected Space Station",
  "gcyr.multiblock.space_shuttle.launch.1": "§cRequires ID Chip!",
  "gcyr.multiblock.space_station.keycard_slot.tooltip": "Configured keycard here",
  "gcyr.multiblock.space_station.pack": "Pack station",
  "gcyr.multiblock.space_station.package_slot.tooltip": "Space Station Package here",
  "gcyr.satellite.dyson_swarm": "Dyson Swarm Satellite",
  "gcyr.satellite.empty": "Empty Satellite",
  "gcyr.satellite.gps": "GPS Satellite",
  "gcyr.satellite.laser": "LASER Satellite",
  "gcyr.solar_system": "Sol",
  "item.gcyr.dyson_construction_drone": "Dyson Construction Drone",
  "item.gcyr.dyson_swarm_satellite": "Dyson Swarm Satellite",
  "item.gcyr.empty_satellite": "Empty Satellite",
  "item.gcyr.gps_satellite": "Gps Satellite",
  "item.gcyr.gps_tracker": "GPS Tracker",
  "item.gcyr.id_chip": "Magnet-strip Identification Chip",
  "item.gcyr.keycard": "Advanced Electric Locking Chip",
  "item.gcyr.laser_satellite": "Laser Satellite",
  "item.gcyr.ore_finder_satellite": "Ore Finder Satellite",
  "item.gcyr.photovoltaic_cell": "Photovoltaic Cell",
  "item.gcyr.smithing_template.space_upgrade.additions_slot_description": "Add Space Suit Part",
  "item.gcyr.smithing_template.space_upgrade.ingredients": "Space Fabric",
  "item.gcyr.space_boots": "Space Boots",
  "item.gcyr.space_chestplate": "Space Chestplate",
  "item.gcyr.space_fabric": "Space Fabric",
  "item.gcyr.space_helmet": "Space Helmet",
  "item.gcyr.space_leggings": "Space Leggings",
  "item.gcyr.space_station_package": "Space Station Package",
  "key.categories.gcyr": "Gregicality Rocketry",
  "key.startRocket": "Start RocketEntity",
  "level.gcyr.mars": "Mars",
  "level.gcyr.mercury": "Mercury",
  "level.gcyr.moon": "Moon",
  "level.gcyr.proxima_centauri_b": "Proxima b",
  "level.gcyr.venus": "Venus",
  "level.overworld": "Earth",
  "material.gcyr.bis_trichloromethyl_benzene": "Bis(trichloromethyl)benzene",
  "material.gcyr.bisalloy_400": "Bisalloy-400",
  "material.gcyr.chromic_acid": "Chromic Acid",
  "material.gcyr.co_mn_br_catalyst": "Co-Mn-Br Catalyst",
  "material.gcyr.cobalt_bromide": "Cobalt Bromide",
  "material.gcyr.dimethylformamide": "Dimethylformamide",
  "material.gcyr.durene": "Durene",
  "material.gcyr.fiberglass": "Fiberglass",
  "material.gcyr.fluorite": "Fluorite",
  "material.gcyr.hydrobromic_acid": "Hydrobromic Acid",
  "material.gcyr.iron_oxide": "Iron Oxide",
  "material.gcyr.kapton_k": "Kapton K",
  "material.gcyr.manganese_acetate": "Manganese Acetate",
  "material.gcyr.manganese_bromide": "Manganese Bromide",
  "material.gcyr.martian_rock_dust": "Martian Rock Dust",
  "material.gcyr.nitroaniline": "Nitroaniline",
  "material.gcyr.oxydianiline": "Oxydianiline",
  "material.gcyr.oxydianiline_sludge": "Oxydianiline Sludge",
  "material.gcyr.para_aramid": "Para-Aramid",
  "material.gcyr.para_phenylenediamine": "Para-Phenylenediamine",
  "material.gcyr.para_xylene": "Para-Xylene",
  "material.gcyr.potassium_chloride": "Potassium Chloride",
  "material.gcyr.pyrometillic_dianhydride": "Pyrometillic Dianhydride",
  "material.gcyr.terephthaloyl_chloride": "Terephthaloyl Chloride",
  "material.gcyr.therephthalic_acid": "Therephthalic Acid",
  "material.gcyr.trinaquadalloy": "Trinaquadalloy",
  "menu.gcyr.back": "Back",
  "menu.gcyr.catalog": "Catalog",
  "menu.gcyr.category": "Category",
  "menu.gcyr.dyson_sphere.collapsed": "DYSON SPHERE COLLAPSED",
  "menu.gcyr.dyson_sphere.implosion_chance": "Chance of implosion: %.2f%%",
  "menu.gcyr.dyson_sphere.needs_maintenance": "DYSON SPHERE REQUIRES MAINTENANCE",
  "menu.gcyr.dyson_sphere.time_since_needed_maintenance": "Time since last maintenance: %s seconds",
  "menu.gcyr.galaxy": "Galaxy",
  "menu.gcyr.gravity": "Gravity",
  "menu.gcyr.launch": "LAUNCH",
  "menu.gcyr.moon": "Moon",
  "menu.gcyr.no_gravity": "No Gravity",
  "menu.gcyr.orbit": "Orbit",
  "menu.gcyr.oxygen": "Oxygen",
  "menu.gcyr.oxygen.false": "Doesn't have oxygen",
  "menu.gcyr.oxygen.true": "Has oxygen",
  "menu.gcyr.planet": "Planet",
  "menu.gcyr.provided": "Provided",
  "menu.gcyr.rocket.thrust": "Thrust: %s m/s",
  "menu.gcyr.rocket.unbuild": "UNBUILD",
  "menu.gcyr.rocket_tier": "Tier %d Rocket",
  "menu.gcyr.save_destination_position": "Save Launch platform position to ID Chip",
  "menu.gcyr.solar_system": "Solar System",
  "menu.gcyr.space_station": "Space Station",
  "menu.gcyr.temperature": "Temperature",
  "menu.gcyr.type": "Type",
  "message.gcyr.invalid_id": "The rocket must have a valid Planet ID Chip.",
  "message.gcyr.no_fuel": "The rocket must be fueled fully. Has %s mB fuel, destination requires %s mB.",
  "message.gcyr.notice_id_changed": "The destination of your Space Station ID chip might have changed. Remember to rewrite the personal destination chip with the new data before setting a new target!",
  "message.gcyr.rocket_not_good_enough": "The rocket doesn't have enough tier %s components to travel to the selected planet.",
  "metaitem.gcyr.satellite_package.has_satellite": "Has satellite or space station",
  "metaitem.planet_id_circuit.id": "Currently selected planet: ",
  "metaitem.planet_id_circuit.pos": "Target Position: (%s,%s,%s)",
  "metaitem.planet_id_circuit.station": "To in-orbit space station (ID: %s)",
  "tagprefix.mars": "Mars %s Ore",
  "tagprefix.mercury": "Mercury %s Ore",
  "tagprefix.moon": "Moon %s Ore",
  "tagprefix.venus": "Venus %s Ore",
  "tooltip.gcyr.spacesuit": "Works as a space suit.",
  "tooltip.gcyr.spacesuit.stored": "Stored Oxygen: %s / %s mB",
  "trim_material.gcyr.space": "Space Suit",
  "trim_pattern.gcyr.space": "Space Suit Upgrade"
}
const chineseLang = {
  "behaviour.satellite.type": "卫星类型: ",
  "block.gcyr.advanced_fuel_tank": "先进流体储罐",
  "block.gcyr.advanced_rocket_motor": "先进火箭发动机",
  "block.gcyr.aerospace_aluminium_casing": "铝航空级机械方块",
  "block.gcyr.airlock_door": "气闸门",
  "block.gcyr.basic_fuel_tank": "基础燃料储罐",
  "block.gcyr.basic_rocket_motor": "基础火箭发动机",
  "block.gcyr.beam_receiver": "波束收集器",
  "block.gcyr.drone_hangar": "无人驾驶飞机机库",
  "block.gcyr.dyson_solar_cell": "戴森太阳能电池",
  "block.gcyr.dyson_sphere_casing": "戴森球机械方块",
  "block.gcyr.dyson_sphere_maintenance_port": "戴森球维护端口",
  "block.gcyr.dyson_system_controller": "戴森系统控制器",
  "block.gcyr.elite_fuel_tank": "精英燃料储罐",
  "block.gcyr.elite_rocket_motor": "精英火箭发动机",
  "block.gcyr.iv_oxygen_spreader": "氧气扩散器(§1IV§r)",
  "block.gcyr.launch_pad": "发射台",
  "block.gcyr.luv_oxygen_spreader": "氧气扩散器(§dLuV§r)",
  "block.gcyr.mars_regolith": "火星表层土",
  "block.gcyr.martian_rock": "火星岩石",
  "block.gcyr.mercury_rock": "水星岩石",
  "block.gcyr.moon_sand": "月沙",
  "block.gcyr.moon_stone": "月石",
  "block.gcyr.rocket_scanner": "火箭扫描仪",
  "block.gcyr.seat": "坐垫",
  "block.gcyr.space_elevator": "太空电梯",
  "block.gcyr.space_elevator_support": "太空电梯支架",
  "block.gcyr.space_station_packager": "空间站组装机",
  "block.gcyr.uhv_oxygen_spreader": "氧气扩散器(§4UHV§r)",
  "block.gcyr.uv_oxygen_spreader": "氧气扩散器(§3UV§r)",
  "block.gcyr.venus_rock": "金星岩石",
  "block.gcyr.venus_sand": "金星沙子",
  "block.gcyr.venusian_regolith": "金星表层土",
  "block.gcyr.zpm_oxygen_spreader": "氧气扩散器(§cZPM§r)",
  "entity.gcyr.rocket": "火箭",
  "gcyr.condition.requires_dyson_sphere.false": "不需要激活戴森球",
  "gcyr.condition.requires_dyson_sphere.true": "需要激活戴森球",
  "gcyr.condition.space": "需要机器在太空中",
  "gcyr.machine.satellite_jammer.jammed": "挤满了%s",
  "gcyr.machine.satellite_jammer.position": "在%s",
  "gcyr.multiblock.rocket.build": "扫描火箭",
  "gcyr.multiblock.rocket.unbuild": "拆解火箭",
  "gcyr.multiblock.space_shuttle.launch.0": "前往选定的空间站",
  "gcyr.multiblock.space_shuttle.launch.1": "§c需要ID芯片!",
  "gcyr.satellite.dyson_swarm": "戴森群卫星",
  "gcyr.satellite.empty": "空的卫星",
  "gcyr.satellite.gps": "GPS卫星",
  "gcyr.satellite.laser": "激光卫星",
  "item.gcyr.dyson_construction_drone": "戴森施工无人机",
  "item.gcyr.dyson_swarm_satellite": "戴森群卫星",
  "item.gcyr.empty_satellite": "空的卫星",
  "item.gcyr.gps_satellite": "GPS卫星",
  "item.gcyr.gps_tracker": "GPS跟踪器",
  "item.gcyr.id_chip": "磁条识别芯片",
  "item.gcyr.keycard": "先进电锁芯片",
  "item.gcyr.laser_satellite": "激光卫星",
  "item.gcyr.ore_finder_satellite": "寻矿卫星",
  "item.gcyr.photovoltaic_cell": "光伏电池",
  "item.gcyr.space_boots": "航空靴子",
  "item.gcyr.space_chestplate": "航空胸甲",
  "item.gcyr.space_fabric": "航空织物",
  "item.gcyr.space_helmet": "航空头盔",
  "item.gcyr.space_leggings": "航空护腿",
  "item.gcyr.space_station_package": "空间站包裹",
  "itemGroup.gcyr.gcyr": "Gregicality Rocketry",
  "key.categories.gcyr": "Gregicality Rocketry",
  "key.startRocket": "启动火箭实体",
  "material.aminophenol": "氨基苯酚",
  "material.bis_trichloromethyl_benzene": "间二(三氯甲基)苯",
  "material.bisalloy_400": "贝斯钢-400",
  "material.chromic_acid": "铬酸",
  "material.co_mn_br_catalyst": "钴-锰-溴催化剂",
  "material.cobalt_bromide": "溴化钴",
  "material.dimethylformamide": "N,N-二甲基甲酰胺",
  "material.durene": "均四甲苯",
  "material.fiberglass": "玻璃纤维",
  "material.fluorite": "氟化钙",
  "material.hydrobromic_acid": "氢溴酸",
  "material.iron_oxide": "氧化铁",
  "material.kapton_k": "聚酰亚胺-K(Kapton K)",
  "material.manganese_acetate": "乙酸锰",
  "material.manganese_bromide": "溴化亚锰",
  "material.martian_rock_dust": "火星岩石粉",
  "material.nitroaniline": "硝基苯胺",
  "material.oxydianiline": "二氨基二苯醚",
  "material.oxydianiline_sludge": "二氨基二苯醚泥浆",
  "material.para_aramid": "对位芳纶",
  "material.para_phenylenediamine": "对苯二胺",
  "material.para_xylene": "对二甲苯",
  "material.potassium_carbonate": "碳酸钾",
  "material.potassium_chloride": "氯化钾",
  "material.potassium_hydroxide": "氢氧化钾",
  "material.pyrometillic_dianhydride": "均苯四甲酸二酐",
  "material.terephthaloyl_chloride": "对苯二甲酰氯",
  "material.therephthalic_acid": "对苯二甲酸",
  "material.trinaquadalloy": "碳化凯金硅岩合金",
  "menu.gcyr.back": "返回",
  "menu.gcyr.catalog": "目录",
  "menu.gcyr.category": "类别",
  "menu.gcyr.dyson_sphere.collapsed": "戴森球塌缩",
  "menu.gcyr.dyson_sphere.implosion_chance": "内爆的几率:%s%%",
  "menu.gcyr.dyson_sphere.needs_maintenance": "戴森球需要维护",
  "menu.gcyr.dyson_sphere.time_since_needed_maintenance": "自上次维护以来的时间:%s秒",
  "menu.gcyr.galaxy": "星系",
  "menu.gcyr.gravity": "重力",
  "menu.gcyr.launch": "发射",
  "menu.gcyr.moon": "月球",
  "menu.gcyr.no_gravity": "无重力",
  "menu.gcyr.orbit": "轨道",
  "menu.gcyr.oxygen": "氧气",
  "menu.gcyr.oxygen.false": "没有氧气",
  "menu.gcyr.oxygen.true": "有氧气",
  "menu.gcyr.planet": "地球",
  "menu.gcyr.provided": "提供",
  "menu.gcyr.save_destination_station": "保存空间站ID到钥匙卡",
  "menu.gcyr.solar_system": "太阳系",
  "menu.gcyr.space_station": "空间站",
  "menu.gcyr.temperature": "温度",
  "menu.gcyr.type": "类型",
  "message.gcyr.invalid_id": "火箭必须有一个有效的行星ID芯片。",
  "message.gcyr.no_fuel": "火箭必须加满燃料，并有有效的行星ID芯片。",
  "message.gcyr.notice_id_changed": "你的空间站ID芯片的目的地可能已经改变了。在设定新目标之前，记得用新数据重写个人目标芯片!",
  "message.gcyr.rocket_not_good_enough": "火箭没有足够的%s层组件前往选定的星球。",
  "metaitem.gcyr.satellite_package.has_satellite": "有卫星或空间站吗",
  "metaitem.planet_id_circuit.id": "当前选择的行星:",
  "metaitem.planet_id_circuit.station": "到在轨空间站(ID: %s)",
  "tagprefix.mars": "火星%s矿石",
  "tagprefix.mercury": "水星%s矿石",
  "tagprefix.moon": "月球%s矿石",
  "tagprefix.venus": "金星%s矿石"
}
const differenceKeys = [...(new Set(Object.keys(englishLang))).difference(new Set(Object.keys(chineseLang))).values()]
const obj = {}
for (let key of differenceKeys) {
  obj[key] = englishLang[key] ?? chineseLang[key]
}
console.log(obj)

const v3 = {}
const rg = /\w/g
const obj2 = {}
for (const key in v3) {
  if (Object.prototype.hasOwnProperty.call(v3, key)) {
    const element = v3[key];
    if (rg.test(element)) {
      obj2[key] = element
    }
  }
}
console.log(obj2)