GTCEuStartupEvents.registry('gtceu:machine', event => {
  const r = event.create('kubejs_super_nu_activer', 'multiblock') as any as Internal.MultiblockMachineBuilder
  r.rotationState(RotationState.NON_Y_AXIS)
  r.pattern(definition => FactoryBlockPattern.start()
    .aisle('AAAAAAAAAAAAAAAA', 'BCCCCCDCCDCCCCCB', 'BCCCCCCDDCCCCCCB', 'BCCCCCCDKCCCCCCB', 'BCCCCCDCCDCCCCCB', 'AAAAAAAAAAAAAAAA')
    .aisle('AEEEEEEEEEEEEEEA', 'CFFFFFFFFFFFFFFC', 'CGGGGGGGGGGGGGGC', 'CGGGGGGGGGGGGGGC', 'CFFFFFFFFFFFFFFC', 'AEEEEEEEEEEEEEEA')
    .aisle('AEEEEEEEEEEEEEEA', 'CFFFFFFFFFFFFFFC', 'CGGGGGGGGGGGGGGC', 'CGGGGGGGGGGGGGGC', 'CFFFFFFFFFFFFFFC', 'AEEEEEEEEEEEEEEA')
    .aisle('AEEAAAAAAAAAAEEA', 'CFFHCCCCCCCCHFFC', 'CGGHCCCCCCCCHGGC', 'CGGHCCCCCCCCHGGC', 'CFFHCCCCCCCCHFFC', 'AEEAAAAAAAAAAEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEA########AEEA', 'CFFC########CFFC', 'CGGC########CGGC', 'CGGC########CGGC', 'CFFC########CFFC', 'AEEA########AEEA')
    .aisle('AEEAAAAAAAAAAEEA', 'CFFHCCCCCCCCHFFC', 'CGGHCCCCCCCCHGGC', 'CGGHCCCCCCCCHGGC', 'CFFHCCCCCCCCHFFC', 'AEEAAAAAAAAAAEEA')
    .aisle('AEEEEEEEEEEEEEEA', 'CFFFFFFFFFFFFFFC', 'CGGGGGGGGGGGGGGC', 'CGGGGGGGGGGGGGGC', 'CFFFFFFFFFFFFFFC', 'AEEEEEEEEEEEEEEA')
    .aisle('AEEEEEEEEEEEEEEA', 'CFFFFFFFFFFFFFFC', 'CGGGGGGGGGGGGGGC', 'CGGGGGGGGGGGGGGC', 'CFFFFFFFFFFFFFFC', 'AEEEEEEEEEEEEEEA')
    .aisle('AAAAAAAAAAAAAAAA', 'BCCCCCCCCCCCCCCB', 'BCCCCCCCCCCCCCCB', 'BCCCCCCCCCCCCCCB', 'BCCCCCCCCCCCCCCB', 'AAAAAAAAAAAAAAAA')
    .where('K', Predicates.controller(Predicates.blocks(definition.get())))
    .where('G', Predicates.blocks('gtceu:naquadria_block'))
    .where('D', Predicates.blocks(GTBlocks.MACHINE_CASING_UEV.get()))
    .where('B', Predicates.blocks('gtceu:naquadah_alloy_frame'))
    .where('H', Predicates.blocks('gtceu:black_matter_frame'))
    .where('C', Predicates.blocks('ae2:quartz_vibrant_glass'))
    .where('A', Predicates.blocks('mekanism:sps_casing'))
    .where('F', Predicates.blocks('gtnn:high_speed_pipe_block'))
    .where('E', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get()))
    .where('#', Predicates.air())
    .build()
  ).recipeTypes([GTRecipeTypes.get('kubejs_super_nu_activer')])
  r.langValue('block.gtceu.kubejs_super_nu_activer')
})

GTCEuStartupEvents.registry('gtceu:recipe_type', e => {
  // create() 方法返回 com.gregtechceu.gtceu.integration.kjs.builders.GTRecipeTypeBuilder
  (e as any).create('kubejs_super_nu_activer')
    .setEUIO('in')
    .setMaxIOSize(5, 5, 5, 5)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.COMPRESSOR)
})