
[HudDisplay-FULL]

	[HudDisplay-FULL.General]
		#Range: 0.1 ~ 10.0
		width = 0.6
		#Range: 0.1 ~ 10.0
		height = 0.6
		#Range: 0.1 ~ 10.0
		scale = 1.0
		#Range: -10.0 ~ 10.0
		xOffset = 0.0
		#Range: -10.0 ~ 10.0
		yOffset = 0.0
		#Range: 0.1 ~ 3.0
		thickness = 1.0
		#Range: 0 ~ 255
		color_red = 0
		#Range: 0 ~ 255
		color_green = 255
		#Range: 0 ~ 255
		color_blue = 0

	[HudDisplay-FULL.ElytraHealth]
		elytra_showHealth = true
		#Range: 0.0 ~ 1.0
		elytra_x = 0.5
		#Range: 0.0 ~ 1.0
		elytra_y = 0.8

	[HudDisplay-FULL.Location]
		location_showReadout = true
		#Range: 0.0 ~ 1.0
		location_x = 0.2
		#Range: 0.0 ~ 1.0
		location_y = 0.8

	[HudDisplay-FULL.FlightPath]
		flightPath_show = true

	[HudDisplay-FULL.PitchLadder]
		#Range: 1 ~ 20
		pitchLadder_degreesPerBar = 20
		pitchLadder_showHorizon = true
		pitchLadder_showLadder = true
		#Range: -360.0 ~ 360.0
		pitchLadder_optimumGlideAngle = -2.0
		#Range: -360.0 ~ 360.0
		pitchLadder_optimumClimbAngle = 55.0
		pitchLadder_showRoll = true
		pitchLadder_reverseRoll = false

	[HudDisplay-FULL.Speed]
		speed_showScale = true
		speed_showReadout = true

	[HudDisplay-FULL.Altitude]
		altitude_showScale = true
		altitude_showReadout = true
		altitude_showHeight = true
		altitude_showGroundInfo = true

	[HudDisplay-FULL.Heading]
		heading_showScale = true
		heading_showReadout = true

	[HudDisplay-FULL.ElytraBombing]
		ebb_show_tnt_count = true
		#Range: 0.0 ~ 1.0
		ebb_tnt_x = 0.6000000238418579
		#Range: 0.0 ~ 1.0
		ebb_tnt_y = 0.800000011920929

